import sqlite3 
variable = sqlite3.connect('database.db')
cursor = variable.cursor()
cursor.execute("CREATE TABLE IF NOT EXISTS DIEREN (id INTEGER PRIMARY KEY AUTOINCREMENT, naam TEXT, beschrijving TEXT, categorie TEXT, status TEXT, leefgebied TEXT, kenmerken TEXT)")
cursor.execute("INSERT OR IGNORE INTO DIEREN (naam, beschrijving, categorie, status, leefgebied, kenmerken) VALUES ('Leeuw', 'De leeuw is een grote katachtige die in Afrika en delen van Azië voorkomt. Ze staan bekend om hun manen en worden vaak de \"koning van de jungle\" genoemd.', 'Katachtigen', 'Kwetsbaar', 'Afrikaanse savanne', 'Enige katachtige die in groepen (troepen) leeft')")
cursor.execute("INSERT OR IGNORE INTO DIEREN (naam, beschrijving, categorie, status, leefgebied, kenmerken) VALUES ('Armoertijger', 'De amoertijger, ook wel Siberische tijger genoemd, is een van de grootste tijgersoorten en komt voor in de bossen van het Russische Verre Oosten. Ze hebben een dikke vacht om zich te beschermen tegen de koude winters.', 'Katachtigen', 'Bedreigd', 'Russisch Verre Oosten (taiga)', 'Dikste vacht van alle tijgerondersoorten, overleeft -40°C')")
cursor.execute("INSERT OR IGNORE INTO DIEREN (naam, beschrijving, categorie, status, leefgebied, kenmerken) VALUES ('Jaguar', 'De jaguar is een grote katachtige die in de regenwouden van Midden- en Zuid-Amerika voorkomt. Ze staan bekend om hun gespierde bouw en krachtige kaken.', 'Katachtigen', 'Bijna bedreigd', 'Midden- en Zuid-Amerika (regenwoud)', 'Bijt door schedels heen, sterkste bijtkracht t.o.v. lichaamsgrootte van alle katachtigen')")
cursor.execute("INSERT OR IGNORE INTO DIEREN (naam, beschrijving, categorie, status, leefgebied, kenmerken) VALUES ('Armoerluipaard', 'Het amoerluipaard, ook wel Siberische luipaard genoemd, is een zeldzame en bedreigde katachtige die voorkomt in de bossen van het Russische Verre Oosten. Ze hebben een dikke vacht en zijn uitstekend aangepast aan koude klimaten.', 'Katachtigen', 'Ernstig bedreigd', 'Oost-Rustland, Noord-China', 'Slechts 130 exemplaren in het wild; kan 3m hoog springen')")

cursor.execute("INSERT OR IGNORE INTO DIEREN (naam, beschrijving, categorie, status, leefgebied, kenmerken) VALUES ('Gorilla', 'De gorilla is een grote mensachtige die in de regenwouden van Afrika voorkomt. Ze staan bekend om hun kracht en sociale gedrag.', 'Mensapen', 'Ernstig bedreigd', 'Centraal-Afrikaanse regenwouden', 'Sterkste mensachtige; kan 10x zijn eigen lichaamsgewicht tillen')")
cursor.execute("INSERT OR IGNORE INTO DIEREN (naam, beschrijving, categorie, status, leefgebied, kenmerken) VALUES ('Chimpansee', 'De chimpansee is een mensachtige die in de bossen van Afrika voorkomt. Ze zijn nauw verwant aan mensen en staan bekend om hun intelligentie en sociale structuren.', 'Mensapen', 'Bedreigd', 'West- en Centraal-Afrika (bossen)', 'Dichtstbijzijnde levende verwant van de mens; gebruikt gereedschap in het wild')")
cursor.execute("INSERT OR IGNORE INTO DIEREN (naam, beschrijving, categorie, status, leefgebied, kenmerken) VALUES ('Uilenkopmeerkat', 'De uilenkopmeerkat is een kleine mensachtige die in de droge gebieden van Afrika voorkomt. Ze hebben een uniek uiterlijk met een ronde kop en grote ogen, waardoor ze lijken op een uil.', 'Mensapen', 'Niet bedreigd', 'West-Afika (Kustbossen)', 'Ronde ogen geven hem een uilen-achtig gezicht; leeft in bomen')")

cursor.execute("INSERT OR IGNORE INTO DIEREN (naam, beschrijving, categorie, status, leefgebied, kenmerken) VALUES ('Brilbeer', 'De brilbeer is een middelgrote beer die voorkomt in de Andes van Zuid-Amerika. Ze staan bekend om de witte vlekken rond hun ogen, die lijken op een bril.', 'Beren', 'Kwetsbaar', 'Andesgebergte (Zuid-Amerika)', 'Enige berensoort die in bomen kan klimmen; vlekken rond ogen lijken op een bril')")

cursor.execute("INSERT OR IGNORE INTO DIEREN (naam, beschrijving, categorie, status, leefgebied, kenmerken) VALUES ('Rode_panda', 'De rode panda is een kleine zoogdier die voorkomt in de bergachtige gebieden van Nepal, India, Bhutan en China. Ze hebben een roodbruine vacht en een lange, pluizige staart.', 'Kleine_Roofdieren', 'Bedreigd', 'Bergachtige gebieden van Nepal, India, Bhutan en China', 'Niet verwant aan de reuzenpanda; heeft een vacht die lijkt op die van een vos')")
cursor.execute("INSERT OR IGNORE INTO DIEREN (naam, beschrijving, categorie, status, leefgebied, kenmerken) VALUES ('Stokstaartje', 'Het stokstaartje is een kleine zoogdier die voorkomt in de droge gebieden van Afrika. Ze staan bekend om hun sociale gedrag en het feit dat ze vaak rechtop staan om hun omgeving in de gaten te houden.', 'Kleine_Roofdieren', 'Niet bedreigd', 'West-Afrika (droge gebieden)', 'Kan rechtop staan om omgeving in de gaten te houden')")
cursor.execute("INSERT OR IGNORE INTO DIEREN (naam, beschrijving, categorie, status, leefgebied, kenmerken) VALUES ('Neusbeer', 'De neusbeer is een kleine zoogdier die voorkomt in de bossen van Midden- en Zuid-Amerika. Ze hebben een lange snuit en een dikke vacht, en staan bekend om hun nieuwsgierige aard.', 'Kleine_Roofdieren', 'Niet bedreigd', 'Midden- en Zuid-Amerika (bossen)', 'Heeft een lange snuit en een dikke vacht')")
cursor.execute("INSERT OR IGNORE INTO DIEREN (naam, beschrijving, categorie, status, leefgebied, kenmerken) VALUES ('Vosmangoest', 'De vosmangoest is een kleine zoogdier die voorkomt in de droge gebieden van Afrika. Ze hebben een roodbruine vacht en staan bekend om hun behendigheid en snelheid.', 'Kleine_Roofdieren', 'Niet bedreigd', 'West-Afrika (droge gebieden)', 'Heeft een roodbruine vacht en is behendig en snel')")
cursor.execute("INSERT OR IGNORE INTO DIEREN (naam, beschrijving, categorie, status, leefgebied, kenmerken) VALUES ('Wasbeer', 'De wasbeer is een kleine zoogdier die voorkomt in Noord- en Zuid-Amerika. Ze hebben een grijze vacht en een kenmerkende zwarte \"masker\" rond hun ogen.', 'Kleine_Roofdieren', 'Niet bedreigd', 'Noord- en Zuid-Amerika (bossen)', 'Heeft een grijze vacht en een kenmerkende zwarte \"masker\" rond hun ogen')")

cursor.execute("INSERT OR IGNORE INTO DIEREN (naam, beschrijving, categorie, status, leefgebied, kenmerken) VALUES ('Californische_zeeleeuw', 'De Californische zeeleeuw is een zeezoogdier dat voorkomt langs de westkust van Noord-Amerika. Ze staan bekend om hun speelse gedrag en worden vaak gezien in dierentuinen en aquaria.', 'Zeedieren', 'Niet bedreigd', 'Westkust van Noord-Amerika', 'Speels gedrag; vaak gezien in dierentuinen en aquaria')")
cursor.execute("INSERT OR IGNORE INTO DIEREN (naam, beschrijving, categorie, status, leefgebied, kenmerken) VALUES ('Gewone_zeehond', 'De gewone zeehond is een zeezoogdier dat voorkomt in de kustwateren van Europa, Noord-Amerika en delen van Azië. Ze hebben een grijze vacht en staan bekend om hun vermogen om zowel op het land als in het water te leven.', 'Zeedieren', 'Niet bedreigd', 'Kustwateren van Europa, Noord-Amerika en delen van Azië', 'Kan zowel op het land als in het water leven; heeft een grijze vacht')")

cursor.execute("INSERT OR IGNORE INTO DIEREN (naam, beschrijving, categorie, status, leefgebied, kenmerken) VALUES ('Giraffe', 'De giraffe is een grote hoefdier die voorkomt in de savannes van Afrika. Ze staan bekend om hun lange nek en benen, en hun unieke vlekkenpatroon.', 'Hoefdieren', 'Kwetsbaar', 'Afrikaanse savanne', 'Langste nek van alle landdieren; unieke vlekkenpatroon voor elke giraffe')")
cursor.execute("INSERT OR IGNORE INTO DIEREN (naam, beschrijving, categorie, status, leefgebied, kenmerken) VALUES ('Okapi', 'De okapi is een middelgrote hoefdier die voorkomt in de regenwouden van Congo. Ze hebben een uniek uiterlijk met een lange nek en strepen op hun benen, waardoor ze lijken op een kruising tussen een giraffe en een zebra.', 'Hoefdieren', 'Bedreigd', 'Regenwouden van Congo', 'Uniek uiterlijk met lange nek en strepen op benen; nauw verwant aan de giraffe')")
cursor.execute("INSERT OR IGNORE INTO DIEREN (naam, beschrijving, categorie, status, leefgebied, kenmerken) VALUES ('Kaapse_buffel', 'De Kaapse buffel is een grote hoefdier die voorkomt in de savannes van Afrika. Ze staan bekend om hun kracht en agressieve gedrag, en worden vaak beschouwd als een van de gevaarlijkste dieren in Afrika.', 'Hoefdieren', 'Kwetsbaar', 'Afrikaanse savanne', 'Krachtig en agressief; wordt vaak beschouwd als een van de gevaarlijkste dieren in Afrika')")
cursor.execute("INSERT OR IGNORE INTO DIEREN (naam, beschrijving, categorie, status, leefgebied, kenmerken) VALUES ('Anoa', 'De anoa is een kleine hoefdier die voorkomt in de regenwouden van Indonesië. Ze hebben een gedrongen lichaam en korte poten, en staan bekend om hun schuwe aard.', 'Hoefdieren', 'Bedreigd', 'Regenwouden van Indonesië', 'Kleine hoefdier met gedrongen lichaam en korte poten; schuwe aard')")
cursor.execute("INSERT OR IGNORE INTO DIEREN (naam, beschrijving, categorie, status, leefgebied, kenmerken) VALUES ('Nijlpaard', 'De nijlpaard is een grote hoefdier die voorkomt in de rivieren en meren van Afrika. Ze staan bekend om hun enorme omvang en agressieve gedrag, en worden vaak beschouwd als een van de gevaarlijkste dieren in Afrika.', 'Hoefdieren', 'Kwetsbaar', 'Rivieren en meren van Afrika', 'Enorme omvang en agressief gedrag; wordt vaak beschouwd als een van de gevaarlijkste dieren in Afrika')")
cursor.execute("INSERT OR IGNORE INTO DIEREN (naam, beschrijving, categorie, status, leefgebied, kenmerken) VALUES ('Olifant', 'De olifant is een grote hoefdier die voorkomt in Afrika en delen van Azië. Ze staan bekend om hun enorme omvang, lange slurf en grote oren, en worden vaak beschouwd als een van de meest intelligente dieren op aarde.', 'Hoefdieren', 'Bedreigd', 'Afrika en delen van Azië', 'Enorme omvang, lange slurf en grote oren; wordt vaak beschouwd als een van de meest intelligente dieren op aarde')")

cursor.execute("INSERT OR IGNORE INTO DIEREN (naam, beschrijving, categorie, status, leefgebied, kenmerken) VALUES ('Pinguïn', 'De pinguïn is een vogel die voorkomt in het zuidelijk halfrond, vooral in Antarctica. Ze staan bekend om hun zwart-witte verenkleed en hun vermogen om te zwemmen.', 'Vogels', 'Niet bedreigd', 'Zuidelijk halfrond (vooral Antarctica)', 'Zwart-witte verenkleed; vermogen om te zwemmen')")
cursor.execute("INSERT OR IGNORE INTO DIEREN (naam, beschrijving, categorie, status, leefgebied, kenmerken) VALUES ('Afrikaanse_vogelsoorten', 'Afrika herbergt een enorme diversiteit aan vogelsoorten, waaronder kleurrijke papegaaien, majestueuze arenden en sierlijke flamingos. Deze vogels spelen een belangrijke rol in de ecosystemen van Afrika.', 'Vogels', 'Niet bedreigd', 'Afrika (diverse habitats)', 'Enorme diversiteit aan vogelsoorten, waaronder papegaaien, arenden en flamingos')")

cursor.execute("INSERT OR IGNORE INTO DIEREN (naam, beschrijving, categorie, status, leefgebied, kenmerken) VALUES ('Krokodil', 'De krokodil is een grote reptiel die voorkomt in de tropische gebieden van Afrika, Azië, Amerika en Australië. Ze staan bekend om hun krachtige kaken en hun vermogen om zowel op het land als in het water te leven.', 'Reptielen', 'Niet bedreigd', 'Tropische gebieden van Afrika, Azië, Amerika en Australië', 'Krachtige kaken; vermogen om zowel op het land als in het water te leven')")
cursor.execute("INSERT OR IGNORE INTO DIEREN (naam, beschrijving, categorie, status, leefgebied, kenmerken) VALUES ('Alligator', 'De alligator is een grote reptiel die voorkomt in de zuidelijke Verenigde Staten en China. Ze lijken op krokodillen, maar hebben een bredere snuit en zijn over het algemeen minder agressief.', 'Reptielen', 'Niet bedreigd', 'Zuidelijke Verenigde Staten en China', 'Lijken op krokodillen; bredere snuit; minder agressief')")
cursor.execute("INSERT OR IGNORE INTO DIEREN (naam, beschrijving, categorie, status, leefgebied, kenmerken) VALUES ('Slangen', 'Slangen zijn een diverse groep reptielen die voorkomen in bijna alle delen van de wereld, behalve Antarctica. Ze variëren in grootte van kleine, onschuldige soorten tot grote, gevaarlijke soorten zoals de anaconda en de zwarte mamba.', 'Reptielen', 'Niet bedreigd', 'Wereldwijd (behalve Antarctica)', 'Variëren in grootte van kleine tot grote soorten')")
cursor.execute("INSERT OR IGNORE INTO DIEREN (naam, beschrijving, categorie, status, leefgebied, kenmerken) VALUES ('Hagedis', 'Hagedissen zijn een diverse groep reptielen die voorkomen in bijna alle delen van de wereld. Ze variëren in grootte van kleine, onschuldige soorten tot grote, indrukwekkende soorten zoals de Komodovaraan.', 'Reptielen', 'Niet bedreigd', 'Wereldwijd', 'Variëren in grootte van kleine tot grote soorten')")

cursor.execute("INSERT OR IGNORE INTO DIEREN (naam, beschrijving, categorie, status, leefgebied, kenmerken) VALUES ('Tropische_rifvissen', 'Tropische rifvissen zijn een diverse groep vissen die voorkomen in de warme, ondiepe wateren van tropische koraalriffen over de hele wereld. Ze staan bekend om hun felle kleuren en unieke patronen.', 'Aquariumdieren', 'Niet bedreigd', 'Tropische koraalriffen wereldwijd', 'Felle kleuren en unieke patronen; belangrijke rol in koraalrif-ecosystemen')")
cursor.execute("INSERT OR IGNORE INTO DIEREN (naam, beschrijving, categorie, status, leefgebied, kenmerken) VALUES ('Koralen', 'Koralen zijn mariene ongewervelde dieren die voorkomen in de warme, ondiepe wateren van tropische koraalriffen over de hele wereld. Ze vormen de structuur van koraalriffen en bieden onderdak aan een enorme diversiteit aan marien leven.', 'Aquariumdieren', 'Niet bedreigd', 'Tropische koraalriffen wereldwijd', 'Vormen de structuur van koraalriffen; bieden onderdak aan marien leven')")
cursor.execute("INSERT OR IGNORE INTO DIEREN (naam, beschrijving, categorie, status, leefgebied, kenmerken) VALUES ('Zoet-en-zoutwatervissen', 'Zoet- en zoutwatervissen zijn een diverse groep vissen die voorkomen in zowel zoetwater- als zoutwateromgevingen over de hele wereld. Ze variëren in grootte van kleine, onschuldige soorten tot grote, indrukwekkende soorten zoals de meerval en de haai.', 'Aquariumdieren', 'Niet bedreigd', 'Wereldwijd', 'Variëren in grootte van kleine tot grote soorten')")

cursor.execute("CREATE TABLE IF NOT EXISTS CATEGORIEEN (id INTEGER PRIMARY KEY AUTOINCREMENT, naam TEXT)")
cursor.execute("INSERT OR IGNORE INTO CATEGORIEEN (naam) VALUES ('Katachtigen')")
cursor.execute("INSERT OR IGNORE INTO CATEGORIEEN (naam) VALUES ('Mensapen')")
cursor.execute("INSERT OR IGNORE INTO CATEGORIEEN (naam) VALUES ('Aquariumdieren')")
cursor.execute("INSERT OR IGNORE INTO CATEGORIEEN (naam) VALUES ('Kleine_Roofdieren')")
cursor.execute("INSERT OR IGNORE INTO CATEGORIEEN (naam) VALUES ('Zeedieren')")
cursor.execute("INSERT OR IGNORE INTO CATEGORIEEN (naam) VALUES ('Hoefdieren')")
cursor.execute("INSERT OR IGNORE INTO CATEGORIEEN (naam) VALUES ('Vogels')")
cursor.execute("INSERT OR IGNORE INTO CATEGORIEEN (naam) VALUES ('Reptielen')")
cursor.execute("INSERT OR IGNORE INTO CATEGORIEEN (naam) VALUES ('Beren')")


# Create users table
cursor.execute("""CREATE TABLE IF NOT EXISTS USERS (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
)""")

# Create favorites table with user_id foreign key
cursor.execute("""CREATE TABLE IF NOT EXISTS FAVORIETEN (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    dier_id INTEGER NOT NULL,
    FOREIGN KEY (user_id) REFERENCES USERS(id),
    FOREIGN KEY (dier_id) REFERENCES DIEREN(id),
    UNIQUE(user_id, dier_id)
)""")

cursor.execute("SELECT * FROM DIEREN JOIN CATEGORIEEN ON CATEGORIEEN.naam = DIEREN.categorie")
variable.commit()
variable.close()