import sqlite3 
variable = sqlite3.connect('database.db')
cursor = variable.cursor()
cursor.execute("CREATE TABLE IF NOT EXISTS dieren (id INTEGER PRIMARY KEY AUTOINCREMENT, naam TEXT, beschrijving TEXT, categorie TEXT)")
cursor.execute("INSERT INTO dieren (naam, beschrijving, categorie) VALUES ('Leeuw', 'De leeuw is een grote katachtige die in Afrika en delen van Azië voorkomt. Ze staan bekend om hun manen en worden vaak de \"koning van de jungle\" genoemd.', 'Katachtigen')")
cursor.execute("INSERT INTO dieren (naam, beschrijving, categorie) VALUES ('Amoertijger', 'De amoertijger, ook wel Siberische tijger genoemd, is een van de grootste tijgersoorten en komt voor in de bossen van het Russische Verre Oosten. Ze hebben een dikke vacht om zich te beschermen tegen de koude winters.', 'Katachtigen')")
cursor.execute("INSERT INTO dieren (naam, beschrijving, categorie) VALUES ('Jaguar', 'De jaguar is een grote katachtige die in de regenwouden van Midden- en Zuid-Amerika voorkomt. Ze staan bekend om hun gespierde bouw en krachtige kaken.', 'Katachtigen')")
cursor.execute("INSERT INTO dieren (naam, beschrijving, categorie) VALUES ('Amoerluipaard', 'Het amoerluipaard, ook wel Siberische luipaard genoemd, is een zeldzame en bedreigde katachtige die voorkomt in de bossen van het Russische Verre Oosten. Ze hebben een dikke vacht en zijn uitstekend aangepast aan koude klimaten.', 'Katachtigen')")
cursor.execute("INSERT INTO dieren (naam, beschrijving, categorie) VALUES ('Gorilla', 'De gorilla is een grote mensachtige die in de regenwouden van Afrika voorkomt. Ze staan bekend om hun kracht en sociale gedrag.', 'Mensapen')")
cursor.execute("INSERT INTO dieren (naam, beschrijving, categorie) VALUES ('Chimpansee', 'De chimpansee is een mensachtige die in de bossen van Afrika voorkomt. Ze zijn nauw verwant aan mensen en staan bekend om hun intelligentie en sociale structuren.', 'Mensapen')")
cursor.execute("INSERT INTO dieren (naam, beschrijving, categorie) VALUES ('Uilenkopmeerkat', 'De uilenkopmeerkat is een kleine mensachtige die in de droge gebieden van Afrika voorkomt. Ze hebben een uniek uiterlijk met een ronde kop en grote ogen, waardoor ze lijken op een uil.', 'Mensapen')")
cursor.execute("INSERT INTO dieren (naam, beschrijving, categorie) VALUES ('Brilbeer', 'De brilbeer is een middelgrote beer die voorkomt in de Andes van Zuid-Amerika. Ze staan bekend om de witte vlekken rond hun ogen, die lijken op een bril.', 'Beren')")
variable.commit()
variable.close()